### ISSUE TITLE
Is access_id a header field?

### ISSUE THREAD

**Issue by cloudscape-germany** [pd/httpie-api-auth#1]
~~I want to use your plugin, however I don't know if you are referring with the access_id in the methods header to a actual header field in a HTTP request? I need to pass along `bearer: 10283190` to my API in the HTTP headers. Is this possible? If not, this would be a feature request.~~

I am know seeing, that it is possible to set HTTP headers with httpie core module:

```
> To set custom headers you can use the Header:Value notation:
> `$ http example.org  User-Agent:Bacon/1.0  'Cookie:valued-visitor=yes;foo=bar' `
```

**Source:** https://github.com/jakubroztocil/httpie#http-headers

**Comment by pd** [comment]
Sorry for the radio silence, I wasn't receiving notifications for this project.

I think you've resolved this yourself? The access_id value is [straight from APIAuth](https://github.com/mgomes/api_auth#how-it-works), and is sent as part of the `Authorization` header.
